//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "studies")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    pub created_at: Option<DateTime>,
    pub configuration: Option<String>,
    pub questions: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::participations::Entity")]
    Participations,
}

impl Related<super::participations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Participations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
